pause
call vcvars32.bat
call variables.bat
@set PATH=%PATH%;%QT_DIRECTORY%;%BOOST_ROOT%;
cmake .. -DCMAKE_BUILD_TYPE=Debug -DSHOW_DEBUG_OUTPUT=ON -DBOOST_ROOT_DIR=%BOOST_ROOT% -DBOOST_INCLUDE_DIR=%BOOST_INCLUDE_DIR% -DBOOST_LIBRARY_DIR=%BOOST_LIBRARY_DIR% -DQT_DIR=%QT_DIRECTORY% -DEXECUTABLE_OUTPUT_PATH=.\Debug_32x -G "NMake Makefiles"
nmake
pause