pause
call vcvars32.bat
call variables.bat
@set PATH=%PATH%;%QT_DIRECTORY%;%BOOST_ROOT%;
cmake .. -DCMAKE_BUILD_TYPE=Release -DSHOW_DEBUG_OUTPUT=OFF -DBOOST_ROOT_DIR=%BOOST_ROOT% -DBOOST_INCLUDE_DIR=%BOOST_INCLUDE_DIR% -DBOOST_LIBRARY_DIR=%BOOST_LIBRARY_DIR% -DQT_DIR=%QT_DIRECTORY% -DEXECUTABLE_OUTPUT_PATH=.\Release_64x -G "NMake Makefiles"
nmake
pause